- name: create user
  hosts: web
  become: yes
  tasks:
  - name: check user exist or not
    ansible.builtin.commnad: id expense
    register: USER #here USER is a variable that gets output from above commnad
    ignore_errors: True

  - name: print the user information
    ansible.builtin.debug:
      msg: "user info: {{ user }}"  