- name: commnad vs shell
  hosts: local
  connection: local
  tasks:
    - name: excute command
      ansible.builtin.shell: ls -lrth > /tmp/output.txt # login to the server and execute command inside
      # command module, just issues the command

    - name: check the process
      ansible.builtin.shell: ps ef | grep ssh
      register: output  

    - name: check the process
      ansible.builtin.command: ps ef | grep ssh
      register: output 